//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microfon
    {
        public int id_microfona { get; set; }
        public string Name { get; set; }
        public string Max_frequency { get; set; }
        public string Min_frequency { get; set; }
        public Nullable<int> id_proizvoditel { get; set; }
        public Nullable<int> id_type_Mic { get; set; }
        public Nullable<int> id_garantii { get; set; }
    
        public virtual Garantiya Garantiya { get; set; }
        public virtual microfon_type microfon_type { get; set; }
        public virtual proizvoditel proizvoditel { get; set; }
    }
}
